name: skillshare_app
description: "SkillShare - App para intercambio de conocimientos Politécnico"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.5
  provider: ^6.0.5
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  # Dependencias UI
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1 # Para generar íconos de la app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets - Corrección de indentación
  assets:
    - assets/images/
    - assets/icons/

  # Fuentes personalizadas (ejemplo)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic